name: personal-page

library:
  source-dirs: src
  exposed-modules:
    - Lib
    - Types
    - Api
    - Handlers
  dependencies:
    - base >= 4.7 && < 5
    - servant-server
    - aeson
    - text
    - bytestring
    - wai
    - warp
    - lucid
    - servant-lucid
    - servant-client
    - openapi3
    - servant-openapi3
    - mtl
    - sqlite-simple
    - servant-auth
    - servant-auth-server
    - wai-cors
    - wai-extra
    - hspec
    - servant-elm
    - elm-bridge
    - filepath
    
executables:
  personal-page-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
      - base
      - personal-page # Nombre de tu proyecto
      
  generate-elm:  # Este es el nuevo
    main: Main.hs
    source-dirs: generate-elm
    dependencies:
      - personal-page       # Hereda tu librería
      - servant-elm         # Para la función generateElmForAPI
      - text                 # Para Data.Text y Data.Text.IO
      - base                 # Para Prelude y Data.Proxy

